### PR TITLE
Add charconv-dev and install gcc-8 g++-8

### PR DESCRIPTION
**Pull request by ilie1988**
Add charconv-dev and install gcc-8 g++-8

### CODE REVIEW

**Comment by jagerman** [comment]
What problem is this solving?  You don't need a PPA for gcc-8 in Bionic, and I can't find a charconv-dev package anywhere.

**Comment by ilie1988** [comment]
It wont compile without charconv-dev on Ubuntu 18.04.

**Comment by ilie1988** [comment]
And On Testnet i get this:

```
2020-10-11 14:35:09.771 I Resolving node address: host=159.69.109.145, port=38156
2020-10-11 14:35:09.771 I Added node: 159.69.109.145:38156
2020-10-11 14:35:09.850 I 0Connect failed to 159.69.109.145:38156
2020-10-11 14:35:09.851 W Failed to connect to any of seed peers, continuing without seeds
```

**Comment by ilie1988** [comment]
> What problem is this solving? You don't need a PPA for gcc-8 in Bionic, and I can't find a charconv-dev package anywhere.

You can't just export gcc-8 g++-8 without first installing it, or am i wrong?

**Comment by jagerman** [comment]
In my bionic chroot:
```
(bionic)root@betwixt:/home/jagerman/src/loki5# apt install charconv-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package charconv-dev
```

**Comment by jagerman** [comment]
Try wiping out your build directory; it may be that a prior build created a build directory for gcc-7 and re-running make isn't picking up the new compiler.

**Comment by ilie1988** [comment]
> In my bionic chroot:
> 
> ```
> (bionic)root@betwixt:/home/jagerman/src/loki5# apt install charconv-dev
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package charconv-dev
> ```

Thats why you need to add `ppa:ubuntu-toolchain-r/test` in order to find it.

**Comment by ilie1988** [comment]
> Try wiping out your build directory; it may be that a prior build created a build directory for gcc-7 and re-running make isn't picking up the new compiler.

I always remove the build directory.

**Comment by ilie1988** [comment]
My Servers SPECS:

```
root@server:~/loki-core# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by ilie1988** [comment]
> And On Testnet i get this:
> 
> ```
> 2020-10-11 14:35:09.771 I Resolving node address: host=159.69.109.145, port=38156
> 2020-10-11 14:35:09.771 I Added node: 159.69.109.145:38156
> 2020-10-11 14:35:09.850 I 0Connect failed to 159.69.109.145:38156
> 2020-10-11 14:35:09.851 W Failed to connect to any of seed peers, continuing without seeds
> ```

This is from me, the ports wont open even tho i've set them to be open, sory about that!

**Comment by jagerman** [comment]
Try bypassing the top-level Makefile and invoke cmake directly:
```
rm -rf build
mkdir build
cd build
cmake -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 
make -j4  # or whatever is appropriate for your system
```

**Comment by ilie1988** [comment]
> Try bypassing the top-level Makefile and invoke cmake directly:
> 
> ```
> rm -rf build
> mkdir build
> cd build
> cmake -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 
> make -j4  # or whatever is appropriate for your system
> ```

This would not be a viable option for users, try compiling Loki-core on a Clean Ubuntu 18.04 and you'll see you will need charconv-dev, like i was saying earlier, you can't export `gcc-8` and `g++-8` if you don't first install it.

**Comment by jagerman** [comment]
The pre-built debian packages for Ubuntu (https://deb.loki.network) *do* get built in a clean 18.04, don't install charconv-dev, and build pretty much exactly like I described.  Like I said, I also don't see where the charconv-dev package comes from at all; it seems like perhaps something coming via a ppa?

**Comment by ilie1988** [comment]
> The pre-built debian packages for Ubuntu (https://deb.loki.network) _do_ get built in a clean 18.04, don't install charconv-dev, and build pretty much exactly like I described. Like I said, I also don't see where the charconv-dev package comes from at all; it seems like perhaps something coming via a ppa?

On Ubuntu 18.04 you have gcc-7 g++7 and to compile Loki-core you need gcc-8 g++8, and to get that installed and then exported i have to add `ppa:ubuntu-toolchain-r/test` `update` then install `gcc-8 g++8` like you can see in the commit. This would be the easiest way to do that anyways. And plus on older systems this is really the only way.

**Comment by jagerman** [comment]
> On Ubuntu 18.04 you have gcc-7 g++7
This is true for the default `gcc` and `g++` packages, but bionic *also* has `gcc-8` and `g++-8` packages in the main repositories (without using the toolchain-r ppa).
> and to compile Loki-core you need gcc-8 g++8,
Right, but these only require `apt install g++-8` on a plain Bionic install.
> and to get that installed and then exported i have to add ppa:ubuntu-toolchain-r/test update then install gcc-8 g++8 like you can see in the commit. This would be the easiest way to do that anyways. And plus on older systems this is really the only way.
This is the part that isn't needed, at least on bionic.  (It would be if you were trying to build from source on xenial, of course.)

**Comment by ilie1988** [comment]
> g++-8

I see, so on Bionic i don't need to add PPA and just install g++8 directly as it has it in the main repos, i wasn't aware of that, i will retry by removing the PPA and all and i'll recompile it, i will get back once is done.

**Comment by ilie1988** [comment]
After i removed the `toolchain-r ppa` and reinstall gcc-8 g++8 from the main repos it worked successfully! I will close this Pull Request as it's not relevant. 

Thanks for the info

**Pull request closed without merging**
