### PR TITLE
Remove miner.cpp

### PR DESCRIPTION
**Pull request by javabudd**
References https://github.com/loki-project/loki-core/issues/1112

### CODE REVIEW

**Comment by Doy-lee** [comment]
Hi, thanks for having a look at the issue and submitting some changes. The issue referenced isn't necessarily about removing `miner.cpp` from the project- there's still a use for in-built software mining, particularly on the Testnet and internal testing to iterate your own blockchain.

What the issue was getting at was removing the requirement to compile `miner.cpp` and link against it when building the wallet, (which relies on the cryptonote_core library), since the mining code has platform specific code we don't care about for mobile targets and don't want to have to work around, as well as untangling miner from cryptonote_core as a library. This also avoids any 3rd party software wanting to link against core not having to work with mining code as well.

wallet

You can see here, that in the dependency graph wallet links to cryptonote_core, and in cryptonote_core's `CMakeList.txt` that compiles `miner.cpp`

The goal here is to move `miner.cpp` away from anything wallet, except the daemon such as a translation unit/target that the daemon compiles/links against.

**Comment by javabudd** [comment]
Still trying to wrap my head around the project and the issue itself. I appreciate the response and will update the PR with what I think will be the necessary changes.

**Comment by jagerman** [comment]
Rather than trying to find somewhere else to put it, I'd suggesting pulling the mining specific files/code into a separate src/miner/ subdirectory and adding that as a dependency only to code that needs it (but not anything the wallet needs).

**Comment by javabudd** [comment]
This

**Pull request closed without merging**
