### PR TITLE
 Move version into top-level CMakeLists.txt

### PR DESCRIPTION
**Pull request by jagerman**
CMake already provides variables to handle the version major/minor/patch
if we give it the dotted version in the `project()` command.  Using it
significantly reduces the amount of macro stuff we have to do in
version.cpp.in, and it seems a little nicer to have it defined in the
project top level rather than buried in a needs-to-beprocessed .cpp
file.

This moves the release codename there, too, so that it stays being
defined in essentially the same place as the version.

This change here requires some minor tweaking of the version generation
code to do it in two steps (when we have git): the first
(`src/version.cpp.in` -> `build/version.cpp.in`) replaces all the main
version variables during cmake configuration, the second
(`build/version.cpp.in` -> `build/version.cpp`) then replaces the
VERSIONTAG at build time.  (Before this commit, there was only version
tag replacement that only happened at build time).

Also bumps the version here to 7.99.0 because dev's version was behind
master's, but should be well ahead of it since we've already merged
things that are not for the 7.x branch.

### CODE REVIEW

**Comment by Doy-lee** [comment]
7.99.0 is a bit weird, just append the branch name to it instead? Its not something that should have to be micromanaged when developing in progress stuff. Git hash + branch should suffice

**Comment by jagerman** [comment]
> 7.99.0 is a bit weird, just append the branch name to it instead?

Being a bit weird is kind of the point: it's really just mean to be a obvious not-a-release-version value that isn't micromanaged at all but just stays to loudly shout "this is not a release branch" until we're ready to actually tag a 8.0.0 testing release.

**Comment by Doy-lee** [comment]
Having '-dev' would do that right? I just don't know how trivial that'd be to add. It avoids the micromanaging of changing the version and re-merging the release version when it can be automated.

**Comment by jagerman** [comment]
> It avoids the micromanaging of changing the version and re-merging the release version when it can be automated.

I don't follow.  You'd never change this version until there's a 8.0.0, and the existing `-tag` conveys much more info than `-branch` would.

**Comment by Doy-lee** [comment]
8.0.0 arrives to master, you then go and update the dev version to be 8.XX.0, or alternatively it produces a 8.0.0-dev. Tag currently only appends '-release' at the moment

**Comment by Doy-lee** [comment]
Maybe you want to distinguish between compatible dev and master branches? But for that purpose we already commit directly to master and merge it back to dev

**Comment by jagerman** [comment]
> Tag currently only appends '-release' at the moment

That's only if it's a tagged release (and even then -- current uploaded binaries don't report release but rather the tag, I assume because they were built before the tag was pushed).  Anything built on `dev` won't be tagged and will get the git tag instead.

I don't really mind changing this to anything else, but what?  Leaving it at 7.1.5 seems wrong and updating it to follow master's version seems more micromanaging.  7.2.0 maybe?

**Comment by jagerman** [comment]
> Maybe you want to distinguish between compatible dev and master branches? But for that purpose we already commit directly to master and merge it back to dev

`dev` is currently already unmergeable to `master`, IMO, and my thinking here is that we would only bump the `dev` version to x.99.0 (or x.2.0 or whatever) once `dev` has gone far enough that the changes there won't make it back onto `master`.

**Comment by jagerman** [comment]
(Also note that I'm not suggesting merging this PR to `master`)

**Comment by Doy-lee** [comment]
Everything in master needs to be merged back to dev, so you would just have to go ahead and do a manual merge (including version changes- so that keeps dev in sync with master).

We can go ahead and try adopt a more strict versioning that clearly distinguishes said case, but I don't think is necessary as whoever makes the calls as to when to merge dev to master knows the implications of doing so.

**Comment by jagerman** [comment]
Updated with a `LOKI_VERSION_SUFFIX` variable that gets append to the version string.  It's set to `-dev` here: we'll want to set it to an empty string when merging to master, and then should be able to leave it untouched forever after.

Produces a full version string such as:
```C++
const char* const LOKI_VERSION_FULL = "7.1.8-822081c2a-dev";
```

**Comment by jagerman** [comment]
Also reset the version to 7.1.8 to match master rather than the 7.99.0 not-really-a-version value.

**Pull request merged**
